name: macOS Interactive Shell
on:
  workflow_dispatch:
    inputs:
      os_version:
        description: 'macOS Version'
        required: true
        default: 'macos-15'
        type: choice
        options:
          - macos-15
          - macos-14
          - macos-13

jobs:
  interactive-shell:
    runs-on: ${{ github.event.inputs.os_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          # This limits access to only YOU (based on your GitHub SSH keys)
          limit-access-to-actor: true